on:
  - push

env:
  UBUNTU_DEPS: cmake make pkg-config libdbus-1-3 libdbus-1-dev xorg-dev

name: Build
jobs:
  build-windows-22:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      # Install dependencies
      - uses: microsoft/setup-msbuild@v1.1

      # Configure and build
      - run: cmake -G "Visual Studio 17 2022" -A x64 .
      - run: msbuild proj.sln /p:configuration=release

      # Upload
      - uses: actions/upload-artifact@v3
        with:
          name: windows-22-bin
          path: Release/proj.exe

  build-windows-19:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Install dependencies
      - uses: microsoft/setup-msbuild@v1.1

      # Configure and build
      - run: cmake -G "Visual Studio 16 2019" -A x64 .
      - run: msbuild proj.sln /p:configuration=release

      # Upload
      - uses: actions/upload-artifact@v3
        with:
          name: windows-19-bin
          path: Release/proj.exe

  build-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Install dependencies
      - run: |
          sudo apt-get update
          sudo apt-get install -y g++ $UBUNTU_DEPS

      # Configure and build
      - run: cmake .
      - run: make -j

      # Upload
      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu-20-bin
          path: proj

  build-ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Install dependencies
      - run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y g++-11 gcc-11 $UBUNTU_DEPS

      # Configure and build
      - run: CXX=g++-11 CC=gcc-11 cmake .
      - run: make -j

      # Upload
      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu-18-bin
          path: proj

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Build
      - run: cmake .
      - run: make -j

      # Upload
      - uses: actions/upload-artifact@v3
        with:
          name: macos-bin
          path: proj

  build-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://releases.nixos.org/nix/nix-2.8.0/install

      # Build
      - run: nix build "git+file://$PWD?submodules=1&shallow=1"
